name: hydroponic
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  syncfusion_flutter_gauges: ^24.2.6
  http: ^1.2.0
  lottie: 3.1.0
  carousel_slider: 4.2.1
  device_preview: ^1.1.0
  flutter_local_notifications: 17.1.1
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  permission_handler: ^11.3.1
  firebase_database: ^10.4.9
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.8
  get_storage: 2.1.1
  syncfusion_flutter_charts: ^24.2.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/icons/
  fonts: 
    - family: Montserrat
      fonts: 
        - asset: fonts/Montserrat.ttf
  uses-material-design: true

