// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANw7Et4kwhmHa79qbul2OZ7Lx-HNCqt5w',
    appId: '1:957134796080:web:74af06316f3f695eae84f5',
    messagingSenderId: '957134796080',
    projectId: 'hydroponic-1cb98',
    authDomain: 'hydroponic-1cb98.firebaseapp.com',
    storageBucket: 'hydroponic-1cb98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGt36xXZZP2f_VbQQpP_Etd-dFp34DR8A',
    appId: '1:957134796080:android:e1bf69456a973f74ae84f5',
    messagingSenderId: '957134796080',
    projectId: 'hydroponic-1cb98',
    storageBucket: 'hydroponic-1cb98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd-k_7m7KfSOC0jpEuNONQ93WmY5Ia4Uk',
    appId: '1:957134796080:ios:ba20b6ca85764299ae84f5',
    messagingSenderId: '957134796080',
    projectId: 'hydroponic-1cb98',
    storageBucket: 'hydroponic-1cb98.appspot.com',
    iosBundleId: 'com.example.hydroponic',
  );
}
